[package]
name = "HippoAggregator"
version = "0.0.0"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'ede36dd00d7c3ba6b86a153b5ddb5da82924fc7f'
subdir = 'aptos-move/framework/aptos-framework'


[addresses]
hippo_aggregator = "89576037b3cc0b89645ea393a47787bb348272c76d6941c574b053672b848039"

